import type { MapEdge, MapNode } from "./types";

export const MAP_WIDTH = 1672;
export const MAP_HEIGHT = 941;

/**
 * 업로드된 평면도 이미지에 맞춘 1차 좌표입니다.
 * 실제 현장 운영 확인 후 입구/출구 역할과 좌표만 조정하면 됩니다.
 */
export const nodes: MapNode[] = [
  {
    id: "GATE_W1",
    name: "메인 입구",
    x: 570,
    y: 830,
    type: "entrance",
    selectable: true,
  },
  {
    id: "GATE_W2",
    name: "우측 출입구",
    x: 1470,
    y: 655,
    type: "exit",
    selectable: true,
  },
  {
    id: "GATE_N",
    name: "상단 출입구",
    x: 535,
    y: 145,
    type: "entrance",
    selectable: true,
  },
  {
    id: "WEST_HALL",
    name: "입구 홀",
    x: 675,
    y: 750,
    type: "junction",
    selectable: false,
  },
  {
    id: "LOBBY_CENTER",
    name: "로비 중앙",
    x: 1085,
    y: 645,
    type: "junction",
    selectable: false,
  },
  {
    id: "NORTH_HALL",
    name: "전시 통로",
    x: 780,
    y: 315,
    type: "junction",
    selectable: false,
  },
  {
    id: "CATERING",
    name: "케이터링",
    x: 820,
    y: 785,
    type: "facility",
    selectable: true,
  },
  {
    id: "PHOTO_ZONE",
    name: "포토존",
    x: 670,
    y: 640,
    type: "facility",
    selectable: true,
  },
  {
    id: "INFO_DESK",
    name: "안내데스크",
    x: 1265,
    y: 505,
    type: "facility",
    selectable: true,
  },
  {
    id: "BOOTH_GATE",
    name: "성과부스 입구",
    x: 1035,
    y: 410,
    type: "junction",
    selectable: false,
  },

  {
    id: "AISLE_01",
    name: "부스 통로 1",
    x: 615,
    y: 190,
    type: "junction",
    selectable: false,
  },
  {
    id: "AISLE_02",
    name: "부스 통로 2",
    x: 715,
    y: 235,
    type: "junction",
    selectable: false,
  },
  {
    id: "AISLE_03",
    name: "부스 통로 3",
    x: 820,
    y: 285,
    type: "junction",
    selectable: false,
  },
  {
    id: "AISLE_04",
    name: "부스 통로 4",
    x: 930,
    y: 335,
    type: "junction",
    selectable: false,
  },
  {
    id: "AISLE_05",
    name: "부스 통로 5",
    x: 1040,
    y: 385,
    type: "junction",
    selectable: false,
  },

  // 위쪽 성과 부스 1~5
  ...[
    [595, 130],
    [710, 175],
    [825, 225],
    [945, 280],
    [1060, 335],
  ].map(
    ([x, y], index): MapNode => ({
      id: `BOOTH_${String(index + 1).padStart(2, "0")}`,
      name: `성과 부스 ${index + 1}`,
      x,
      y,
      type: "booth",
      selectable: true,
    })
  ),

  // 아래쪽 성과 부스 6~10
  ...[
    [645, 235],
    [755, 285],
    [865, 335],
    [975, 385],
    [1085, 435],
  ].map(
    ([x, y], index): MapNode => ({
      id: `BOOTH_${String(index + 6).padStart(2, "0")}`,
      name: `성과 부스 ${index + 6}`,
      x,
      y,
      type: "booth",
      selectable: true,
    })
  ),
];

export const edges: MapEdge[] = [
  {
    id: "E_W1_WEST",
    from: "GATE_W1",
    to: "WEST_HALL",
    distance: 4.8,
    widthM: 3.9,
    zone: "gate",
    crowdRegion: "west",
    bidirectional: true,
  },
  {
    id: "E_W2_WEST",
    from: "GATE_W2",
    to: "WEST_HALL",
    distance: 4.3,
    widthM: 3.9,
    zone: "gate",
    crowdRegion: "west",
    bidirectional: true,
  },
  {
    id: "E_WEST_LOBBY",
    from: "WEST_HALL",
    to: "LOBBY_CENTER",
    distance: 12.5,
    widthM: 5.5,
    zone: "lobby",
    crowdRegion: "central",
    bidirectional: true,
  },
  {
    id: "E_GATE_N_NORTH",
    from: "GATE_N",
    to: "NORTH_HALL",
    distance: 5.2,
    widthM: 3.9,
    zone: "gate",
    crowdRegion: "north",
    bidirectional: true,
  },
  {
    id: "E_NORTH_LOBBY",
    from: "NORTH_HALL",
    to: "LOBBY_CENTER",
    distance: 9.0,
    widthM: 4.0,
    zone: "lobby",
    crowdRegion: "north",
    bidirectional: true,
  },
  {
    id: "E_WEST_CATERING",
    from: "WEST_HALL",
    to: "CATERING",
    distance: 6.4,
    widthM: 4.5,
    zone: "facility",
    crowdRegion: "west",
    bidirectional: true,
  },
  {
    id: "E_NORTH_PHOTO",
    from: "NORTH_HALL",
    to: "PHOTO_ZONE",
    distance: 4.8,
    widthM: 4.0,
    zone: "facility",
    crowdRegion: "north",
    bidirectional: true,
  },
  {
    id: "E_LOBBY_INFO",
    from: "LOBBY_CENTER",
    to: "INFO_DESK",
    distance: 5.6,
    widthM: 3.2,
    zone: "facility",
    crowdRegion: "central",
    bidirectional: true,
  },
  {
    id: "E_LOBBY_BOOTH_GATE",
    from: "LOBBY_CENTER",
    to: "BOOTH_GATE",
    distance: 16.0,
    widthM: 3.0,
    zone: "lobby",
    crowdRegion: "central",
    bidirectional: true,
  },
  {
    id: "E_NORTH_BOOTH_GATE",
    from: "NORTH_HALL",
    to: "BOOTH_GATE",
    distance: 11.0,
    widthM: 3.6,
    zone: "lobby",
    crowdRegion: "north",
    bidirectional: true,
  },

  {
    id: "E_GATE_A5",
    from: "BOOTH_GATE",
    to: "AISLE_05",
    distance: 3.0,
    widthM: 2.8,
    zone: "booth",
    crowdRegion: "booth",
    bidirectional: true,
  },
  {
    id: "E_A1_A2",
    from: "AISLE_01",
    to: "AISLE_02",
    distance: 4.0,
    widthM: 2.8,
    zone: "booth",
    crowdRegion: "booth",
    bidirectional: true,
  },
  {
    id: "E_A2_A3",
    from: "AISLE_02",
    to: "AISLE_03",
    distance: 4.2,
    widthM: 2.8,
    zone: "booth",
    crowdRegion: "booth",
    bidirectional: true,
  },
  {
    id: "E_A3_A4",
    from: "AISLE_03",
    to: "AISLE_04",
    distance: 4.2,
    widthM: 2.8,
    zone: "booth",
    crowdRegion: "booth",
    bidirectional: true,
  },
  {
    id: "E_A4_A5",
    from: "AISLE_04",
    to: "AISLE_05",
    distance: 4.0,
    widthM: 2.8,
    zone: "booth",
    crowdRegion: "booth",
    bidirectional: true,
  },

  ...Array.from({ length: 5 }, (_, index): MapEdge => ({
    id: `E_A${index + 1}_B${index + 1}`,
    from: `AISLE_0${index + 1}`,
    to: `BOOTH_0${index + 1}`,
    distance: 2.4,
    widthM: 2.2,
    zone: "booth",
    crowdRegion: "booth",
    bidirectional: true,
  })),

  ...Array.from({ length: 5 }, (_, index): MapEdge => ({
    id: `E_A${index + 1}_B${index + 6}`,
    from: `AISLE_0${index + 1}`,
    to: `BOOTH_${String(index + 6).padStart(2, "0")}`,
    distance: 2.4,
    widthM: 2.2,
    zone: "booth",
    crowdRegion: "booth",
    bidirectional: true,
  })),
];

export const selectableNodes = nodes.filter((node) => node.selectable);
